In [1]:
#import pandas 
import pandas as pd

In [2]:
#reading my csv file into jupyter notebook
df = pd.read_csv('Completed_Encampment_Management_Team_Operations_Since_2021.csv')
df.head()

,LOCATION;DISTRICT;SENSITIVITY ZONE;INTERVENTION;OPERATION START DATE;OPERATION END DATE,Unnamed: 1
0,9th St and Pine St (cul-de-sac);D3;High;Deep C...,NaN
1,42nd & Dover;D1;High;Closure;March 28 2023;Mar...,NaN
2,42nd between MLK & Telegraph;D1;Low;Deep Clean...,NaN
3,Lake Merritt Park: 1200 Lakeshore;D2;High;Part...,NaN
4,West between 35th and 36th St;D3;Low;Deep Clea...,NaN

In [3]:
#splitting my string into separate columns
df=df['LOCATION;DISTRICT;SENSITIVITY ZONE;INTERVENTION;OPERATION START DATE;OPERATION END DATE'].str.split(";", expand=True)
df

,0,1,2,3,4,5,6
0,9th St and Pine St (cul-de-sac),D3,High,Deep Cleaning,March 30 2023,March 30 2023,None
1,42nd & Dover,D1,High,Closure,March 28 2023,March 29 2023,None
2,42nd between MLK & Telegraph,D1,Low,Deep Cleaning (Northside) and Closure (Southside),March 28 2023,March 29 2023,None
3,Lake Merritt Park: 1200 Lakeshore,D2,High,Partial Closure,March 27 2023,March 28 2023,None
4,West between 35th and 36th St,D3,Low,Deep Clean (Westside) and Closure (Eastside),March 27 2023,March 27 2023,None
...,...,...,...,...,...,...,...
673,Center St between 13th St and 14th St,D3,High,Deep Cleaning,April 04 2023,April 04 2023,None
674,Mandela Pkwy between 13th and 14th,D3,High,Deep Cleaning,April 04 2023,April 04 2023,None
675,13th St between Center and Mandela Pkwy,D3,High,Deep Cleaning,April 04 2023,April 04 2023,None
676,Cypress Memorial Park,D3,High,Deep Cleaning,April 04 2023,April 04 2023,None
677,High St between Oakport St and Coliseum Way,D5,Low,Deep Cleaning,April 03 2023,April 03 2023,None

In [11]:
#converting the dataframe into an excel file
df.to_excel("camp_mgmt.xlsx")